# Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=false
springdoc.swagger-ui.url=/event-booking-swagger.yml

# Postgres Database Config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${APP_DATASOUCE_URL}
spring.datasource.username=${APP_DATASOURCE_USERNAME}
spring.datasource.password=${APP_DATASOURCE_PASSWORD}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.continue-on-error=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Server Config
server.port=${APP_SERVER_PORT}
spring.config.import=optional:file:.env[.properties]
debug=${APP_DEBUG}

# JWT Config
app.jwt.secret=${APP_SECRET}
app.jwt-expiration-milliseconds=${APP_JWT_EXPIRATION_MILLISECONDS}

# Notification Service Config
app.event-reminder.cron=${APP_EVENT_REMINDER_CRON}
app.notification.event-reminder-weeks=${APP_NOTIFICATION_EVENT_REMINDER_WEEKS}

# Email Config
spring.mail.host=${APP_NOTIFICATION_HOST}
spring.mail.port=${APP_NOTIFICATION_PORT}
spring.mail.username=${APP_NOTIFICATION_EMAIL}
spring.mail.password=${APP_NOTIFICATION_PASSWORD}
spring.mail.properties.mail.smtp.auth=${APP_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${APP_MAIL_SMTP_STARTTLS_ENABLE}



