spring.application.name=proof-of-concept-configurable-modules
server.port=8080

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/sample
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.modules-path=/modules
spring.liquibase.enabled=false
