# Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=false
springdoc.swagger-ui.url=/event-booking-swagger.yml

# Postgres Database Config
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/event-booking}
spring.datasource.username=${APP_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${APP_DATASOURCE_PASSWORD:12345}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.continue-on-error=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Config
server.port=${APP_SERVER_PORT:8080}
spring.config.import=optional:file:.env.development.local[.properties]
debug=${APP_DEBUG:false}

# JWT Config
app.jwt.secret=${APP_SECRET:secret}
app.jwt-expiration-milliseconds=${APP_JWT_EXPIRATION_MILLISECONDS:86400000}

# Notification Service Config
app.event-reminder.cron=${APP_EVENT_REMINDER_CRON:0 0 8 * * MON,WED,FRI}
app.notification.event-reminder-weeks=${APP_NOTIFICATION_EVENT_REMINDER_WEEKS:9}

# Email Config

spring.mail.host=${APP_NOTIFICATION_HOST:smtp.gmail.com}
spring.mail.port=${APP_NOTIFICATION_PORT:587}
spring.mail.username=${APP_NOTIFICATION_EMAIL:asquarep00@gmail.com}
spring.mail.password=${APP_NOTIFICATION_PASSWORD:djhz sepw kakd nses}
spring.mail.properties.mail.smtp.auth=${APP_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${APP_MAIL_SMTP_STARTTLS_ENABLE:true}
