spring.application.name=proof-of-concept-configurable-modules
server.port=8080

# Swagger Config
springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=true
#springdoc.swagger-ui.url=/event-booking-swagger.yml

springdoc.swagger-ui.enabled=true

# Swagger UI path (default, but explicit)
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.use-root-path=false

spring.mvc.pathmatch.matching-strategy=path_pattern_parser

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/sample
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.modules-path=/modules
spring.liquibase.enabled=false

# JWT Config
app.jwt.secret=${APP_SECRET:U29tZVNlY3VyZVN0cmluZ1RocmVldHlGcm9tSmF2YVNlY3VyaXR5Rm9ySFRTUjUxMg==}
app.jwt-expiration-milliseconds=${APP_JWT_EXPIRATION_MILLISECONDS:86400000}

# Spring Dev Tools
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.thymeleaf.cache=false

spring.devtools.restart.additional-paths=src/main/resources
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false



# LOGGING
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG